spring.application.name=rest_linea
server.port=9000

cors.allowed-origins=http://localhost:8005,http://localhost:3000
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=Authorization,Content-Type
spring.web.cors.allow-credentials=true



security.jwt.secret-key=y17XAVaH5JxCdb5lABQ0rK3wu7XWQMXLRzd3SUKnEm4p42IJaz2DfPgZekoRcd7lDnHCEkNwi4YEyjnpi37a5A
security.jwt.expiration-time=3600000

# security.jwt.secret-key=${JWT_SECRET} 
# security.jwt.expiration-time=${JWT_EXPIRATION:3600000}

spring.datasource.url=jdbc:mysql://localhost:3306/LineaDesk?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=amohdi_linea
spring.datasource.password=linea_desk2026
# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}

## Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
